name: Dummy API tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      email: ${{ secrets.APPID }}
    
    steps:
      - name: Checkout main branch from GitHub
        run: |
          echo ${{ secrets.APPID }}
          echo ${{ env.APPID }}
        